name: terra_dart_sdk_extensions
description: A lightweight library containing extensions for the terra ecosystem
version: 1.0.5
homepage: https://github.com/TerraMystics
repository: https://github.com/TerraMystics/Terra.Dart.Extensions
documentation: "https://docs.terra.money/"
funding:
  - https://www.buymeacoffee.com/dangenius
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  common_utils: ^2.1.0
  random_string: ^2.3.1
  hex: ^0.2.0
  decimal: ^2.3.2
  protobuf: ^2.1.0
  hash: ^1.0.4
